### ISSUE TITLE
Inexact comparison of floating-point numbers in insta tests

### ISSUE THREAD

**Issue by Andlon** [mitsuhiko/insta#316]
I often have a need for comparing snapshots with some *tolerance*. I write a lot of numerical code, and although for some code I want to really be exact, for many things I need to be able to provide some amount of "tolerance", typically in the form of a relative or absolute error.

There are several reasons for this:
- I don't want tests to break just because I reordered a floating-point summation.
- The result is non-deterministic due to e.g. parallel computation.
- In some cases I simply want to give quite a bit of leeway for the result and I'm more interested in the "trend" of the result (e.g. by plotting graphs and verifying that they satisfy expectations). Here I might for example only want `insta` tests to fail if some numbers deviate by more than 1% compared to the current reference value (which has been manually confirmed).

I'm not sure exactly how such functionality could look like in `insta`, as I'm not familiar with the inner workings, but I assume it would not work with `Debug` output, and could only work with serialized snapshots comparisons, such as JSON. This also raises a question of *granularity*: What if you have different "tolerances" for different numbers?

My motivation for writing this is to see if there is more interest in having this kind of functionality in `insta`. If so, we can flesh it out more together.

**Comment by mitsuhiko** [comment]
Insta fundamentally compares strings. There is not much that exists today to make the actual comparison "fuzzy". This is something that probably would need to be addressed differently than today but I'm not sure what a good approach would be yet. In some ways if the snapshot is parsable then it could be loaded in structural form and specific fuzziness could be applied. Eg: instead of comparing `Debug` to `Debug` it would compare a parsed version of `Debug` with another parsed version of `Debug` etc.

**Comment by Andlon** [comment]
Huh, using redactions for this is a clever idea, @mitsuhiko! Looking forward to trying it out :-)
