### ISSUE TITLE
`insta review` with trailing newline

### ISSUE THREAD

**Issue by grovesNL** [mitsuhiko/insta#39]
If we intentionally place a newline at the end of a string (i.e. testing a snapshot of terminal output), inline snapshot comparisons will work as expected if we manually populate the inline snapshot. However if we run `cargo insta review` and accept the output, the snapshot fails because the last newline is removed.

It looks like the [newline is removed intentionally](https://github.com/mitsuhiko/insta/blob/097b67205b2cb9c09f234843650895fc7408f23f/src/runtime.rs#L422) to allow placing `"###` on a separate line, but perhaps we can distinguish between these cases?

For example, if we have a simple test with a snapshot that hasn't been populated yet:
```rust
insta::assert_snapshot_matches!("\n", @"");
```

Running `cargo insta review` notes the difference correctly:
```
-old snapshot
+new results
─────────────
"\n"
──────┬──────
    1 ⋮+
    2 ⋮+
──────┴──────
```

If we accept this output, the snapshot is unchanged and remains as `""`. If we manually place `"\n"` as the snapshot then everything works again.

**Comment by max-sixty** [comment]
This is right, though I think for a different reason.

[Here](https://github.com/mitsuhiko/insta/blob/master/cargo-insta/src/inline.rs#L91), `.lines` is called and this loses new lines an the end of the string (you can even see it in the docs example https://doc.rust-lang.org/std/primitive.str.html#method.lines)

Is that right?

If so, what's the best solution? 
- Manually check for a newline character in the snapshot and add one if so?
- Run the comparison after stripping newline characters from the end, so at least the test will pass, even though the value will have an additional `\n` at its end?
  - I had a go at the 2nd, it does change the output for single-line-input, multi-line-output strings

(re the above link - it shouldn't hit that line since it doesn't start with the `⋮` character, here's the branch: https://github.com/mitsuhiko/insta/blob/097b67205b2cb9c09f234843650895fc7408f23f/src/runtime.rs#L386)

**Comment by grovesNL** [comment]
Ah ok, that makes sense about the branch.

In that case maybe we could `split` on `\n` and trim the optional `\r` instead of using `lines` here. [`allow_trailing_empty` appears to control this behavior internally](https://github.com/rust-lang/rust/blob/e34d4ae8692f93155cbf1135ebea4c3fd37abf4e/src/libcore/str/mod.rs#L3086), so `split` should include the final newline if I understand correctly.

Alternatively I suppose we check for optional trailing newlines being removed by `lines` and add it back in afterwards.

**Comment by mitsuhiko** [comment]
Small update on this: I merged @max-sixty's branch now.

**Comment by max-sixty** [comment]
We can close this now

**Comment by mitsuhiko** [comment]
Closing this then :)
