### ISSUE TITLE
Return values from `allow_duplicates!`

### ISSUE THREAD

**Issue by ok-nick** [mitsuhiko/insta#530]
I want to propagate errors to my test function, but `allow_duplicates!` doesn't return anything. Maybe it should return a generic?

**Comment by max-sixty** [comment]
Could you give an example?

**Comment by ok-nick** [comment]
```rust
#[test]
fn test_foo() -> Result<()> {
  allow_duplicates! {
    some_function_that_returns_result()?;
  }?;

  Ok(())
}
```

Not sure if what I'm asking is possible with the current design. Perhaps it'd be better if you can specify a closure for `allow_duplicates!`?
```rust
allow_duplicates!(|| -> Result<()> {
  // code here
})
```

**Comment by max-sixty** [comment]
`allow_duplicates!` is designed to allow the snapshot macros to work within them. Those pass or panic rather than return results.

for example:

```rust
insta::allow_duplicates! {
    for x in (0..10).step_by(2) {
        let is_even = x % 2 == 0;
        insta::assert_debug_snapshot!(is_even, @"true");
    }
}
```

Possibly there's a case where we want to run the snapshot macro but then separately return something? But then do we need the thing we're returning as part of the `insta` context?

**Comment by ok-nick** [comment]
The behavior I'm looking for actually is already supported. My main issue was having to explicitly specify the type for the Result that's returned from inside `allow_duplicates!`, since the macro is internally wrapping everything in a closure.
